"""initial schema

Revision ID: 1ae0937d3650
Revises:
Create Date: 2026-07-22 13:23:37.732863
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "1ae0937d3650"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("actor", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_resource_id"), "audit_events", ["resource_id"], unique=False
    )
    op.create_table(
        "incidents",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("active_dedupe_key", sa.String(length=255), nullable=True),
        sa.Column(
            "severity", sa.Enum("P0", "P1", "P2", "P3", name="incidentseverity"), nullable=False
        ),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("environment", sa.String(length=64), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OPEN",
                "INVESTIGATING",
                "DIAGNOSED",
                "NEEDS_HUMAN",
                "AWAITING_APPROVAL",
                "EXECUTING",
                "MITIGATED",
                "RESOLVED",
                "CLOSED",
                "CANCELLED",
                "FAILED",
                name="incidentstatus",
            ),
            nullable=False,
        ),
        sa.Column("alert_count", sa.Integer(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("active_dedupe_key"),
    )
    op.create_index("ix_incident_service_status", "incidents", ["service", "status"], unique=False)
    op.create_index(op.f("ix_incidents_environment"), "incidents", ["environment"], unique=False)
    op.create_index(op.f("ix_incidents_fingerprint"), "incidents", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_incidents_service"), "incidents", ["service"], unique=False)
    op.create_index(op.f("ix_incidents_status"), "incidents", ["status"], unique=False)
    op.create_table(
        "integration_events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("tenant_key", sa.String(length=128), nullable=False),
        sa.Column("event_id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("payload_digest", sa.String(length=64), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "tenant_key", "event_id", name="uq_integration_event"),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("topic", sa.String(length=128), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("PENDING", "PROCESSING", "SENT", "FAILED", name="outboxstatus"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("sent_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_idempotency_key"),
    )
    op.create_index(op.f("ix_outbox_status"), "outbox", ["status"], unique=False)
    op.create_index(op.f("ix_outbox_topic"), "outbox", ["topic"], unique=False)
    op.create_table(
        "runbook_documents",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("source_uri", sa.String(length=1000), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=True),
        sa.Column("environment", sa.String(length=64), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_uri"),
    )
    op.create_index(
        op.f("ix_runbook_documents_checksum"), "runbook_documents", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_runbook_documents_environment"), "runbook_documents", ["environment"], unique=False
    )
    op.create_index(
        op.f("ix_runbook_documents_service"), "runbook_documents", ["service"], unique=False
    )
    op.create_table(
        "alerts",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("incident_id", sa.String(length=40), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=False),
        sa.Column("fingerprint", sa.String(length=128), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("labels", sa.JSON(), nullable=False),
        sa.Column("annotations", sa.JSON(), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source", "external_id", name="uq_alert_source_external"),
    )
    op.create_index(op.f("ix_alerts_fingerprint"), "alerts", ["fingerprint"], unique=False)
    op.create_index(op.f("ix_alerts_incident_id"), "alerts", ["incident_id"], unique=False)
    op.create_table(
        "conversation_bindings",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("incident_id", sa.String(length=40), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("tenant_key", sa.String(length=128), nullable=False),
        sa.Column("chat_id", sa.String(length=255), nullable=False),
        sa.Column("root_message_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "tenant_key", "incident_id", name="uq_incident_conversation"
        ),
    )
    op.create_index(
        op.f("ix_conversation_bindings_incident_id"),
        "conversation_bindings",
        ["incident_id"],
        unique=False,
    )
    op.create_table(
        "investigation_runs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("incident_id", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "BUDGET_EXHAUSTED",
                "FAILED",
                "CANCELLED",
                name="investigationstatus",
            ),
            nullable=False,
        ),
        sa.Column("step_budget", sa.Integer(), nullable=False),
        sa.Column("steps_used", sa.Integer(), nullable=False),
        sa.Column("state", sa.JSON(), nullable=False),
        sa.Column("diagnosis", sa.JSON(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investigation_runs_incident_id"),
        "investigation_runs",
        ["incident_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investigation_runs_status"), "investigation_runs", ["status"], unique=False
    )
    op.create_table(
        "proposed_actions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("incident_id", sa.String(length=40), nullable=False),
        sa.Column("action_type", sa.String(length=64), nullable=False),
        sa.Column("target_environment", sa.String(length=64), nullable=False),
        sa.Column("service", sa.String(length=128), nullable=False),
        sa.Column("parameters", sa.JSON(), nullable=False),
        sa.Column("risk", sa.Enum("LOW", "MEDIUM", "HIGH", name="actionrisk"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING_APPROVAL",
                "APPROVED",
                "REJECTED",
                "EXECUTING",
                "EXECUTED",
                "FAILED",
                "EXPIRED",
                name="actionstatus",
            ),
            nullable=False,
        ),
        sa.Column("requester", sa.String(length=255), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["incident_id"],
            ["incidents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("idempotency_key"),
    )
    op.create_index(
        op.f("ix_proposed_actions_action_type"), "proposed_actions", ["action_type"], unique=False
    )
    op.create_index(
        op.f("ix_proposed_actions_expires_at"), "proposed_actions", ["expires_at"], unique=False
    )
    op.create_index(
        op.f("ix_proposed_actions_incident_id"), "proposed_actions", ["incident_id"], unique=False
    )
    op.create_index(
        op.f("ix_proposed_actions_service"), "proposed_actions", ["service"], unique=False
    )
    op.create_index(
        op.f("ix_proposed_actions_status"), "proposed_actions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_proposed_actions_target_environment"),
        "proposed_actions",
        ["target_environment"],
        unique=False,
    )
    op.create_table(
        "runbook_chunks",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("document_id", sa.String(length=40), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("heading", sa.String(length=500), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("keywords", sa.JSON(), nullable=False),
        sa.Column("embedding", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["runbook_documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("document_id", "ordinal", name="uq_runbook_chunk_ordinal"),
    )
    op.create_index(
        op.f("ix_runbook_chunks_checksum"), "runbook_chunks", ["checksum"], unique=False
    )
    op.create_index(
        op.f("ix_runbook_chunks_document_id"), "runbook_chunks", ["document_id"], unique=False
    )
    op.create_table(
        "action_executions",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("action_id", sa.String(length=40), nullable=False),
        sa.Column("executor", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("output", sa.JSON(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["proposed_actions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id", name="uq_execution_action"),
    )
    op.create_index(
        op.f("ix_action_executions_action_id"), "action_executions", ["action_id"], unique=False
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("action_id", sa.String(length=40), nullable=False),
        sa.Column("approver", sa.String(length=255), nullable=False),
        sa.Column(
            "decision", sa.Enum("APPROVED", "REJECTED", name="approvaldecision"), nullable=False
        ),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["action_id"],
            ["proposed_actions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("action_id", name="uq_approval_action"),
    )
    op.create_index(op.f("ix_approvals_action_id"), "approvals", ["action_id"], unique=False)
    op.create_table(
        "investigation_jobs",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "RUNNING",
                "COMPLETED",
                "BUDGET_EXHAUSTED",
                "FAILED",
                "CANCELLED",
                name="investigationstatus",
            ),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("locked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["investigation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", name="uq_investigation_job_run"),
    )
    op.create_index(
        op.f("ix_investigation_jobs_run_id"), "investigation_jobs", ["run_id"], unique=False
    )
    op.create_index(
        op.f("ix_investigation_jobs_status"), "investigation_jobs", ["status"], unique=False
    )
    op.create_table(
        "run_events",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["investigation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "sequence", name="uq_run_event_sequence"),
    )
    op.create_index(op.f("ix_run_events_event_type"), "run_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_run_events_run_id"), "run_events", ["run_id"], unique=False)
    op.create_table(
        "tool_calls",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("tool_name", sa.String(length=128), nullable=False),
        sa.Column("arguments", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("SUCCESS", "ERROR", "TIMEOUT", name="toolexecutionstatus"),
            nullable=False,
        ),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["investigation_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tool_calls_run_id"), "tool_calls", ["run_id"], unique=False)
    op.create_index(op.f("ix_tool_calls_status"), "tool_calls", ["status"], unique=False)
    op.create_index(op.f("ix_tool_calls_tool_name"), "tool_calls", ["tool_name"], unique=False)
    op.create_table(
        "evidence",
        sa.Column("id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=40), nullable=False),
        sa.Column("tool_call_id", sa.String(length=40), nullable=False),
        sa.Column("source_type", sa.String(length=64), nullable=False),
        sa.Column("source_uri", sa.String(length=1000), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("attributes", sa.JSON(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["investigation_runs.id"],
        ),
        sa.ForeignKeyConstraint(
            ["tool_call_id"],
            ["tool_calls.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_evidence_checksum"), "evidence", ["checksum"], unique=False)
    op.create_index(op.f("ix_evidence_run_id"), "evidence", ["run_id"], unique=False)
    op.create_index(op.f("ix_evidence_source_type"), "evidence", ["source_type"], unique=False)
    op.create_index(op.f("ix_evidence_tool_call_id"), "evidence", ["tool_call_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_evidence_tool_call_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_source_type"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_run_id"), table_name="evidence")
    op.drop_index(op.f("ix_evidence_checksum"), table_name="evidence")
    op.drop_table("evidence")
    op.drop_index(op.f("ix_tool_calls_tool_name"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_status"), table_name="tool_calls")
    op.drop_index(op.f("ix_tool_calls_run_id"), table_name="tool_calls")
    op.drop_table("tool_calls")
    op.drop_index(op.f("ix_run_events_run_id"), table_name="run_events")
    op.drop_index(op.f("ix_run_events_event_type"), table_name="run_events")
    op.drop_table("run_events")
    op.drop_index(op.f("ix_investigation_jobs_status"), table_name="investigation_jobs")
    op.drop_index(op.f("ix_investigation_jobs_run_id"), table_name="investigation_jobs")
    op.drop_table("investigation_jobs")
    op.drop_index(op.f("ix_approvals_action_id"), table_name="approvals")
    op.drop_table("approvals")
    op.drop_index(op.f("ix_action_executions_action_id"), table_name="action_executions")
    op.drop_table("action_executions")
    op.drop_index(op.f("ix_runbook_chunks_document_id"), table_name="runbook_chunks")
    op.drop_index(op.f("ix_runbook_chunks_checksum"), table_name="runbook_chunks")
    op.drop_table("runbook_chunks")
    op.drop_index(op.f("ix_proposed_actions_target_environment"), table_name="proposed_actions")
    op.drop_index(op.f("ix_proposed_actions_status"), table_name="proposed_actions")
    op.drop_index(op.f("ix_proposed_actions_service"), table_name="proposed_actions")
    op.drop_index(op.f("ix_proposed_actions_incident_id"), table_name="proposed_actions")
    op.drop_index(op.f("ix_proposed_actions_expires_at"), table_name="proposed_actions")
    op.drop_index(op.f("ix_proposed_actions_action_type"), table_name="proposed_actions")
    op.drop_table("proposed_actions")
    op.drop_index(op.f("ix_investigation_runs_status"), table_name="investigation_runs")
    op.drop_index(op.f("ix_investigation_runs_incident_id"), table_name="investigation_runs")
    op.drop_table("investigation_runs")
    op.drop_index(op.f("ix_conversation_bindings_incident_id"), table_name="conversation_bindings")
    op.drop_table("conversation_bindings")
    op.drop_index(op.f("ix_alerts_incident_id"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_fingerprint"), table_name="alerts")
    op.drop_table("alerts")
    op.drop_index(op.f("ix_runbook_documents_service"), table_name="runbook_documents")
    op.drop_index(op.f("ix_runbook_documents_environment"), table_name="runbook_documents")
    op.drop_index(op.f("ix_runbook_documents_checksum"), table_name="runbook_documents")
    op.drop_table("runbook_documents")
    op.drop_index(op.f("ix_outbox_topic"), table_name="outbox")
    op.drop_index(op.f("ix_outbox_status"), table_name="outbox")
    op.drop_table("outbox")
    op.drop_table("integration_events")
    op.drop_index(op.f("ix_incidents_status"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_service"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_fingerprint"), table_name="incidents")
    op.drop_index(op.f("ix_incidents_environment"), table_name="incidents")
    op.drop_index("ix_incident_service_status", table_name="incidents")
    op.drop_table("incidents")
    op.drop_index(op.f("ix_audit_events_resource_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_table("audit_events")
    bind = op.get_bind()
    for name in (
        "toolexecutionstatus",
        "approvaldecision",
        "actionstatus",
        "actionrisk",
        "investigationstatus",
        "outboxstatus",
        "incidentstatus",
        "incidentseverity",
    ):
        sa.Enum(name=name).drop(bind, checkfirst=False)
    # ### end Alembic commands ###
